### ISSUE TITLE
Lean [Perf Fixed]

### ISSUE THREAD

**Issue by LeanxModulostk** [Magisk-Modules-Alt-Repo/submission#199]
**ID**: PerfFixed
**Name**: 𝙇𝙚𝙖𝙣 [Perf Fixed]
**Description**:  This module prevents your device from reducing its performance, which can be useful for games or applications that require high performance. su -c leanperf / leanperfoff
**Link**: https://github.com/LeanxModulostk/PerfFixed
**Source code**: None

**Comment by Atrate** [comment]
Fixed performance mode is a debug property that should not be used in "normal" circumstances. You'd get users complaining about overheating, battery health and in the end, due to thermal throttling, the performance would be reduced compared to a normal setup.

There's better ways of setting almost-fixed core frequencies and that's by modifying the current governor with apps like Kernel Adiutor or other similar apps.
