### ISSUE TITLE
[Module] Magisk Autoboot

### ISSUE THREAD

**Issue by anasfanani** [Magisk-Modules-Alt-Repo/submission#210]
### ID

magisk-autoboot

### Name

Magisk Autoboot

### Description

a Magisk module to enable automatic booting/for turning on of your Android device when it's connected to a charger or USB.

### Module repository link

https://github.com/anasfanani/magisk-autoboot

**Comment by DerGoogler** [comment]
I really don't have that much experience with modifying boot images, but since this repo (MMAR) targets [AMM](https://github.com/Androidacy/MagiskModuleManager) and [MMRL](https://github.com/DerGoogler/MMRL) you'll need to declare an property in your `module.prop` so that user know that this module modifys the boot image

```properties
# [...]
changeBoot=true
```

**Comment by anasfanani** [comment]
Thankyou for response, I have update my `module.prop`.

**Comment by DerGoogler** [comment]
Approved.

You module will available under https://github.com/Magisk-Modules-Alt-Repo/magisk-autoboot

@anasfanani
