### ISSUE TITLE
[Takedown] NavBar_Resize

### ISSUE THREAD

**Issue by DerGoogler** [Magisk-Modules-Alt-Repo/submission#232]
### ID

NavBar_Resize

### Name

36DPI NavBar AOSP

### Module repository link

https://github.com/Magisk-Modules-Alt-Repo/NavBar_Resize_AOSP

### Takedown Request Reason

@CrazyBytesVE you module development haven't received any updates since more than 2 years.

Need second opinion on this @tytydraco @Atrate @HuskyDG

**Comment by Atrate** [comment]
I'd say it depends on whether it's broken just on A14 (/A13) or broken in general. If the former, I'd leave it for a couple of months/years, as A14 is still pretty new and the module could come in handy to some people. Otherwise, I'd take it down or request @CrazyBytesVE to post a compatibility notice in the README.
